name: Download external Helm chart
# 工作流运行时显示名称
run-name: ${{ github.actor }} is learning GitHub Actions
# 怎样触发工作流
on: 
 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]
   
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v4       
        with:
          version: 'latest'

      - name: Add & update repo
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Download chart tarball
        run: |
          helm pull bitnami/nginx --version 15.1.0   # 会下载 nginx-15.1.0.tgz
