# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流######
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    # - name: Login to Harbor Hub
    #   uses: docker/login-action@v2.2.0
    #   with:
    #     registry: harbor.develop.ynlxkj.cn
    #     username: ${{ secrets.USER_NAME }}
    #     password: ${{ secrets.USER_PASSWORD }}
    #     logout: false
        
    - name: Login to Aliyun Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIYUN_USER }}
        password: ${{ secrets.ALIYUN_PASSWD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        # skopeo copy docker://docker.io/mysql:8.0.33 docker://harbor.develop.ynlxkj.cn/public/mysql:8.0.33
        # skopeo copy docker://registry.k8s.io/kube-apiserver:v1.28.2 docker://harbor.develop.ynlxkj.cn/public/kube-apiserver:v1.28.2
        # skopeo copy docker://docker.io/tomcat:9.0.91-jdk21-temurin-jammy docker://harbor.develop.ynlxkj.cn/public/tomcat:9.0.91-jdk21-temurin-jammy
        # skopeo copy docker://docker.io/bitnami/redis-cluster:7.2.5-debian-12-r0 docker://harbor.develop.ynlxkj.cn/public/redis-cluster:7.2.5-debian-12-r0
        skopeo copy docker://docker.io/mysql:9.0.1-oraclelinux9 docker://registry.cn-hangzhou.aliyuncs.com/planck/mysql:9.0.1-oraclelinux9
        skopeo copy docker://docker.io/mysql:8.4 docker://registry.cn-hangzhou.aliyuncs.com/planck/mysql:8.4
        skopeo copy docker://docker.io/redis:7.4.0 docker://registry.cn-hangzhou.aliyuncs.com/planck/redis:7.4.0
        skopeo copy docker://docker.io/redis:7.4.0-alpine3.20 docker://registry.cn-hangzhou.aliyuncs.com/planck/redis:7.4.0-alpine3.20
        skopeo copy docker://docker.io/ubuntu:24.04 docker://registry.cn-hangzhou.aliyuncs.com/planck/ubuntu:24.04
        skopeo copy docker://docker.io/nginx:1.27 docker://registry.cn-hangzhou.aliyuncs.com/planck/nginx:1.27
        skopeo copy docker://docker.io/elasticsearch:8.15.0 docker://registry.cn-hangzhou.aliyuncs.com/planck/elasticsearch:8.15.0
        skopeo copy docker://docker.io/elasticsearch:7.17.23 docker://registry.cn-hangzhou.aliyuncs.com/planck/elasticsearch:7.17.23
        
