# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流######
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

###### 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v4.2.0
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0

    # - name: Login to Harbor Hub
    #   uses: docker/login-action@v3.0.0
    #   with:
    #     registry: harbor.develop.ynlxkj.cn
    #     username: ${{ secrets.USER_NAME }}
    #     password: ${{ secrets.USER_PASSWORD }}
    #     logout: false
        
    - name: Login to Aliyun Hub
      uses: docker/login-action@v3.0.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIYUN_USER }}
        password: ${{ secrets.ALIYUN_PASSWD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        # skopeo copy docker://docker.io/alpine:3.21.3 docker://registry.cn-hangzhou.aliyuncs.com/planck/alpine:3.21.3
        skopeo copy docker://kibana:7.12.0 docker://registry.cn-hangzhou.aliyuncs.com/planck/kibana:7.12.0
        # skopeo copy docker://ghcr.io/flannel-io/flannel-cni-plugin:v1.6.2-flannel1 docker://registry.cn-hangzhou.aliyuncs.com/planck/flannel-cni-plugin:v1.6.2-flannel1
        # skopeo copy docker://ghcr.io/flannel-io/flannel:v0.26.4 docker://registry.cn-hangzhou.aliyuncs.com/planck/flannel:v0.26.4
        # skopeo copy docker://docker.io/calico/typha:v3.29.2 docker://registry.cn-hangzhou.aliyuncs.com/planck/calico-typha:v3.29.2
        # skopeo copy docker://docker.io/calico/kube-controllers:v3.29.2 docker://registry.cn-hangzhou.aliyuncs.com/planck/calico-kube-controllers:v3.29.2
        # skopeo copy docker://docker.io/calico/csi:v3.29.2 docker://registry.cn-hangzhou.aliyuncs.com/planck/calico-csi:v3.29.2
        # skopeo copy docker://docker.io/calico/node-driver-registrar:v3.29.2 docker://registry.cn-hangzhou.aliyuncs.com/planck/calico-node-driver-registrar:v3.29.2
        # skopeo copy docker://docker.io/calico/pod2daemon-flexvol:v3.29.2 docker://registry.cn-hangzhou.aliyuncs.com/planck/calico-pod2daemon-flexvol:v3.29.2
        # skopeo copy docker://docker.io/calico/apiserver:v3.29.2 docker://registry.cn-hangzhou.aliyuncs.com/planck/calico-apiserver:v3.29.2
        # img_tag=v3.26.2
        # skopeo copy docker://docker.io/calico/cni:$img_tag docker://registry.cn-hangzhou.aliyuncs.com/planck/calico-node:$img_tag
        # skopeo copy docker://docker.io/calico/node:$img_tag docker://registry.cn-hangzhou.aliyuncs.com/planck/calico-cni:$img_tag
        # skopeo copy docker://docker.io/calico/kube-controllers:$img_tag docker://registry.cn-hangzhou.aliyuncs.com/planck/calico-kube-controllers:$img_tag
        

        
        
        
