# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流######
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Harbor Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: harbor.develop.ynlxkj.cn
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.USER_PASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        # skopeo copy docker://docker.io/mysql:8.0.33 docker://harbor.develop.ynlxkj.cn/public/mysql:8.0.33
        skopeo copy docker://docker.io/apache/skywalking-oap-server:9.6.0 docker://harbor.develop.ynlxkj.cn/public/skywalking-oap-server:9.6.0
        skopeo copy docker://docker.io/apache/skywalking-ui:9.6.0 docker://harbor.develop.ynlxkj.cn/public/skywalking-ui:9.6.0
        skopeo copy docker://docker.io/apache/skywalking-java-agent:9.0.0-alpine docker://harbor.develop.ynlxkj.cn/public/skywalking-java-agent:9.0.0-alpine




